---
title: "Lab_exercise#2_octavio"
author: "Octavio, Jessa"
date: "2024-03-07"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)
library(xml2)

```

Product 1
```{r}
  link1 <- "https://www.amazon.com/ESR-Compatible-Military-Grade-Protection-Scratch/product-reviews/B099JVC9HL/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews"
  
session <- bow(link1,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  product_category <- rep("Phone Case", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews1= data.frame()
  productreviews1 <- rbind(productreviews1, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

 
link2 <- "https://www.amazon.com/ESR-Compatible-Military-Grade-Protection-Scratch/product-reviews/B099JVC9HL/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=2"

  session <- bow(link2,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Phone Case", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews2= data.frame()
  productreviews2 <- rbind(productreviews2, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)


link3 <- "https://www.amazon.com/ESR-Compatible-Military-Grade-Protection-Scratch/product-reviews/B099JVC9HL/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=3"

  session <- bow(link3,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Phone Case", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews3= data.frame()
  productreviews3 <- rbind(productreviews3, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link4 <- "https://www.amazon.com/ESR-Compatible-Military-Grade-Protection-Scratch/product-reviews/B099JVC9HL/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=4"

  session <- bow(link4,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Phone Case", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews4= data.frame()
  productreviews4 <- rbind(productreviews4, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link5 <- "https://www.amazon.com/ESR-Compatible-Military-Grade-Protection-Scratch/product-reviews/B099JVC9HL/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=5"

  session <- bow(link5,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Phone Case", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews5= data.frame()
  productreviews5 <- rbind(productreviews5, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)
 
productrev1 <- rbind(productreviews5,productreviews1,productreviews2,productreviews3,productreviews4) 
write.csv(productrev1, file = "product1.csv")
```

Product 2
```{r}
link1 <- "https://www.amazon.com/CLUCI-Leather-Crossbody-Backpack/product-reviews/B0C5LC519H/ref=acr_dp_hist_5?ie=UTF8&reviewerType=all_reviews"

  session <- bow(link1,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Sling Bag", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews1= data.frame()
  productreviews1 <- rbind(productreviews1, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)


link2 <- "https://www.amazon.com/CLUCI-Leather-Crossbody-Backpack/product-reviews/B0C5LC519H/ref=acr_dp_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=2"

  session <- bow(link2,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Sling Bag", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews2= data.frame()
  productreviews2 <- rbind(productreviews2, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)


link3 <- "https://www.amazon.com/CLUCI-Leather-Crossbody-Backpack/product-reviews/B0C5LC519H/ref=acr_dp_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=3"

  session <- bow(link3,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Sling Bag", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews3= data.frame()
  productreviews3 <- rbind(productreviews3, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)


link4 <- "https://www.amazon.com/CLUCI-Leather-Crossbody-Backpack/product-reviews/B0C5LC519H/ref=acr_dp_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=4"

  session <- bow(link4,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Sling Bag", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews4= data.frame()
  productreviews4 <- rbind(productreviews4, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link5 <- "https://www.amazon.com/CLUCI-Leather-Crossbody-Backpack/product-reviews/B0C5LC519H/ref=acr_dp_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=5"

  session <- bow(link5,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Sling Bag", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews5= data.frame()
  productreviews5 <- rbind(productreviews5, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)
 productrev2 <- rbind(productreviews1,productreviews2,productreviews3,productreviews4,productreviews5)
 write.csv(productrev2, file = "product2.csv")
```

Product 3
```{r}
link1 <- "https://www.amazon.com.au/Katy-Perry-Killer-Queen-Parfum/product-reviews/B00ENL4HJW/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews"

  session <- bow(link1,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Perfume", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews1= data.frame()
  productreviews1 <- rbind(productreviews1, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link2 <- "https://www.amazon.com.au/Katy-Perry-Killer-Queen-Parfum/product-reviews/B00ENL4HJW/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=2" 

  session <- bow(link2,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Perfume", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews2= data.frame()
  productreviews2 <- rbind(productreviews2, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link3 <- "https://www.amazon.com.au/Katy-Perry-Killer-Queen-Parfum/product-reviews/B00ENL4HJW/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=3"

  session <- bow(link3,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Perfume", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews3= data.frame()
  productreviews3 <- rbind(productreviews3, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link4 <- "https://www.amazon.com.au/Katy-Perry-Killer-Queen-Parfum/product-reviews/B00ENL4HJW/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=4"

  session <- bow(link4,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  product_category <- rep("Perfume", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews4= data.frame()
  productreviews4 <- rbind(productreviews4, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link5 <- "https://www.amazon.com.au/Katy-Perry-Killer-Queen-Parfum/product-reviews/B00ENL4HJW/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=5"

  session <- bow(link5,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Perfume", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews5= data.frame()
  productreviews5 <- rbind(productreviews5, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)
 productrev3 <- rbind(productreviews1,productreviews2,productreviews3,productreviews4,productreviews5)
 write.csv(productrev3, file = "product3.csv")
```

Product 4
```{r}
link1 <- "https://www.amazon.com.au/Anne-Klein-Gold-Tone-Stainless-AK/product-reviews/B00AJS4L3U/ref=acr_dp_hist_5?ie=UTF8&reviewerType=all_reviews"

  session <- bow(link1,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Watch", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews1= data.frame()
  productreviews1 <- rbind(productreviews1, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link2 <- "https://www.amazon.com.au/Anne-Klein-Gold-Tone-Stainless-AK/product-reviews/B00AJS4L3U/ref=acr_dp_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=2"

  session <- bow(link2,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Watch", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews2= data.frame()
  productreviews2 <- rbind(productreviews2, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link3 <- "https://www.amazon.com.au/Anne-Klein-Gold-Tone-Stainless-AK/product-reviews/B00AJS4L3U/ref=acr_dp_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=3"

  session <- bow(link3,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Watch", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews3= data.frame()
  productreviews3 <- rbind(productreviews3, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link4 <- "https://www.amazon.com.au/Anne-Klein-Gold-Tone-Stainless-AK/product-reviews/B00AJS4L3U/ref=acr_dp_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=4"

  session <- bow(link4,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Watch", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews4= data.frame()
  productreviews4 <- rbind(productreviews4, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link5 <- "https://www.amazon.com.au/Anne-Klein-Gold-Tone-Stainless-AK/product-reviews/B00AJS4L3U/ref=acr_dp_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=5"

  session <- bow(link5,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Watch", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews5= data.frame()
  productreviews5 <- rbind(productreviews5, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)
 productrev4 <- rbind(productreviews1,productreviews2,productreviews3,productreviews4,productreviews5)
 write.csv(productrev4, file = "product4.csv")
```

Product 5
```{r}
link1 <- "https://www.amazon.com.au/Wet-Wild-Eyeshadow-Shimmering/product-reviews/B09NX8R28P/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews"

  session <- bow(link1,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Makeup", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews1= data.frame()
  productreviews1 <- rbind(productreviews1, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link2 <- "https://www.amazon.com.au/Wet-Wild-Eyeshadow-Shimmering/product-reviews/B09NX8R28P/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=2"

  session <- bow(link2,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Makeup", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews2= data.frame()
  productreviews2 <- rbind(productreviews2, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link3 <- "https://www.amazon.com.au/Wet-Wild-Eyeshadow-Shimmering/product-reviews/B09NX8R28P/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=3"

  session <- bow(link3,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Makeup", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews3= data.frame()
  productreviews3 <- rbind(productreviews3, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link4 <- "https://www.amazon.com.au/Wet-Wild-Eyeshadow-Shimmering/product-reviews/B09NX8R28P/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=4"

  session <- bow(link4,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Makeup", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews4= data.frame()
  productreviews4 <- rbind(productreviews4, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)
 
link5 <- "https://www.amazon.com.au/Wet-Wild-Eyeshadow-Shimmering/product-reviews/B09NX8R28P/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=5"

  session <- bow(link5,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Makeup", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews5= data.frame()
  productreviews5 <- rbind(productreviews5, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)
 productrev5 <- rbind(productreviews1,productreviews2,productreviews3,productreviews4,productreviews5)
 write.csv(productrev5, file = "product5.csv")
```

Product 6
```{r}
link1 <- "https://www.amazon.com.au/Shy-Velvet-Womens-Sleeves-Crossover/product-reviews/B0B1NXR6QP/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews"

  session <- bow(link1,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Dress", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews1= data.frame()
  productreviews1 <- rbind(productreviews1, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link2 <- "https://www.amazon.com.au/Shy-Velvet-Womens-Sleeves-Crossover/product-reviews/B0B1NXR6QP/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=2"

  session <- bow(link2,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Dress", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews2= data.frame()
  productreviews2 <- rbind(productreviews2, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link3 <- "https://www.amazon.com.au/Shy-Velvet-Womens-Sleeves-Crossover/product-reviews/B0B1NXR6QP/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=3"

  session <- bow(link3,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Dress", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews3= data.frame()
  productreviews3 <- rbind(productreviews3, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link4 <- "https://www.amazon.com.au/Shy-Velvet-Womens-Sleeves-Crossover/product-reviews/B0B1NXR6QP/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=4"

  session <- bow(link4,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Dress", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews4= data.frame()
  productreviews4 <- rbind(productreviews4, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link5 <- "https://www.amazon.com.au/Shy-Velvet-Womens-Sleeves-Crossover/product-reviews/B0B1NXR6QP/ref=acr_dpx_hist_5?ie=UTF8&reviewerType=all_reviews&pageNumber=5"

  session <- bow(link5,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Dress", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews5= data.frame()
  productreviews5 <- rbind(productreviews5, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)
 productrev6 <- rbind(productreviews1,productreviews2,productreviews3,productreviews4,productreviews5)
 write.csv(productrev6, file = "product6.csv")
```

Product 7
```{r}
link1 <- "https://www.amazon.com.au/Cicy-Bell-Womens-Sunflower-Graphic/product-reviews/B088TW7XXC/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews"

  session <- bow(link1,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("T-shirt", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews1= data.frame()
  productreviews1 <- rbind(productreviews1, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link2 <- "https://www.amazon.com.au/Cicy-Bell-Womens-Sunflower-Graphic/product-reviews/B088TW7XXC/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=2"

  session <- bow(link2,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("T-shirt", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews2= data.frame()
  productreviews2 <- rbind(productreviews2, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link3 <- "https://www.amazon.com.au/Cicy-Bell-Womens-Sunflower-Graphic/product-reviews/B088TW7XXC/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=3"

  session <- bow(link3,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("T-shirt", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews3= data.frame()
  productreviews3 <- rbind(productreviews3, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link4 <- "https://www.amazon.com.au/Cicy-Bell-Womens-Sunflower-Graphic/product-reviews/B088TW7XXC/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=4"

  session <- bow(link4,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("T-shirt", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews4= data.frame()
  productreviews4 <- rbind(productreviews4, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link5 <- "https://www.amazon.com.au/Cicy-Bell-Womens-Sunflower-Graphic/product-reviews/B088TW7XXC/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=5"

  session <- bow(link5,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("T-shirt", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews5= data.frame()
  productreviews5 <- rbind(productreviews5, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)
 productrev7 <- rbind(productreviews1,productreviews2,productreviews3,productreviews4,productreviews5)
 write.csv(productrev7, file = "product7.csv")
```

Product 8
```{r}
link1 <- "https://www.amazon.com.au/SWAROVSKI-Attract-Trilogy-Pierced-Earrings/product-reviews/B07DPRW46T/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=1"

  session <- bow(link1,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Earrings", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews1= data.frame()
  productreviews1 <- rbind(productreviews1, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link2 <- "https://www.amazon.com.au/SWAROVSKI-Attract-Trilogy-Pierced-Earrings/product-reviews/B07DPRW46T/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=2"

  session <- bow(link2,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Earrings", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews2= data.frame()
  productreviews2 <- rbind(productreviews2, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link3 <- "https://www.amazon.com.au/SWAROVSKI-Attract-Trilogy-Pierced-Earrings/product-reviews/B07DPRW46T/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=3"

  session <- bow(link3,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Earrings", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews3= data.frame()
  productreviews3 <- rbind(productreviews3, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link4 <- "https://www.amazon.com.au/SWAROVSKI-Attract-Trilogy-Pierced-Earrings/product-reviews/B07DPRW46T/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=4"

  session <- bow(link4,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Earrings", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews4= data.frame()
  productreviews4 <- rbind(productreviews4, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link5 <- "https://www.amazon.com.au/SWAROVSKI-Attract-Trilogy-Pierced-Earrings/product-reviews/B07DPRW46T/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=5"

  session <- bow(link5,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Earrings", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews5= data.frame()
  productreviews5 <- rbind(productreviews5, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)
 productrev8 <- rbind(productreviews1,productreviews2,productreviews3,productreviews4,productreviews5)
 write.csv(productrev8, file = "product8.csv")
```

Product 9
```{r}
link1 <- "https://www.amazon.com.au/LifeStraw-Stainless-Integrated-Insulated-/product-reviews/B08G1ZDNWP/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews"

  session <- bow(link1,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Water Bottle", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews1= data.frame()
  productreviews1 <- rbind(productreviews1, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))

  
 Sys.sleep(5)


link2 <- "https://www.amazon.com.au/LifeStraw-Stainless-Integrated-Insulated/product-reviews/B08G1ZDNWP/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=2"

  session <- bow(link2,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Water Bottle", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews2= data.frame()
  productreviews2 <- rbind(productreviews2, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link3 <- "https://www.amazon.com.au/LifeStraw-Stainless-Integrated-Insulated/product-reviews/B08G1ZDNWP/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=3"

  session <- bow(link3,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Water Bottle", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews3= data.frame()
  productreviews3 <- rbind(productreviews3, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link4 <- "https://www.amazon.com.au/LifeStraw-Stainless-Integrated-Insulated/product-reviews/B08G1ZDNWP/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=4"

  session <- bow(link4,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Water Bottle", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews4= data.frame()
  productreviews4 <- rbind(productreviews4, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)

link5 <- "https://www.amazon.com.au/LifeStraw-Stainless-Integrated-Insulated/product-reviews/B08G1ZDNWP/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_revie&pageNumber=5"

  session <- bow(link5,
               user_agent = "For Educational Purpose")

  scrapeNodes <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- rep("Water Bottle", 10)

  product_name <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  product_name <- rep(product_name, 10)
  product_name <- product_name[1:10]
  
  verified_reviews <-scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")
  verified_reviews <-verified_reviews[1:10]
  
  product_reviewer <- scrapeNodes("span.a-profile-name")
  product_reviewer <- product_reviewer[1:10]
  
  product_review <- scrapeNodes("span.a-size-base.review-text")
  product_review <- product_review[1:10]
  
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
  product_date <- product_date[1:10]
  
  product_rating <- scrapeNodes("span.a-icon-alt")
  product_rating <- product_rating[1:10]
  
  productreviews5= data.frame()
  productreviews5 <- rbind(productreviews5, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
 Sys.sleep(5)
 productrev9 <- rbind(productreviews1,productreviews2,productreviews3,productreviews4,productreviews5)
 write.csv(productrev9, file = "product9.csv")
```

Product 10
```{r}
productrev10 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Michael-Kors-Womens-Travel-Wristlet/product-reviews/B08KFKWRM1/ref=cm_cr_dp_d_show_all_btm", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Wallet"
  product_name <- "Michael Kors Jet Set Travel double Zip Wristlet"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev10 <- rbind(productrev10, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
 write.csv(productrev10, file = "product10.csv")
```

Product 11

```{r}
productrev11 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Invisible-String-Patrice-Karst/product-reviews/031648623X/ref=cm_cr_dp_d_show_all_btm", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Book"
  product_name <- "The Invisible String: 1 Paperback  Picture Book, 11 December 2018"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev11 <- rbind(productrev11, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev11, file = "product11.csv")
```

Product 12
```{r}
productrev12 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com/i7-12650H-GeForce-Display-Backlit-AN515-58-781P/product-reviews/B0C5RSZ6N2/ref=cm_cr_dp_d_show_all_btm", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Laptop"
  product_name <- "RAcer Nitro 5 Gaming Laptop | Intel 12th Gen i7-12650H | NVIDIA GeForce RTX 4060 Laptop GPU | 15.6 FHD 144Hz IPS Display | 16GB DDR5 | 1TB Gen 4 SSD | Killer Wi-Fi 6 | RGB Backlit KB | AN515-58-781P"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev12 <- rbind(productrev12, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev12, file = "product12.csv")
```

Product 13
```{r}
productrev13 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Jergens-Moisturizer-Essential-Indulgent-Moisturization/product-reviews/B07QBN245V/ref=cm_cr_dp_d_show_all_btm", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Lotion"
  product_name <- "Jergens Lavender Body Butter Body and Hand Lotion, Moisturizer for Women, 7 Fl Oz (Pack of 1), with Essential Oils for Indulgent Moisturization White"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev13 <- rbind(productrev13, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev13, file = "product13.csv")
```

Product 14
```{r}
productrev14 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com/IBOANN-Blocking-Glasses-Fashion-Eyeglasses/product-reviews/B0B779BLJH/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Eyeglasses"
  product_name <- "IBOANN 3 Pack Blue Light Blocking Glasses Women/Men, Round Fashion Retro Frame, Vintage Fake Eyeglasses with Clear Lens"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev14 <- rbind(productrev14, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev14, file = "product14.csv")
```

```{r}
productrev15 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Champion-Womens-GT18H-Classic-T-Shirt/product-reviews/B07SCKRK78/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "T-shirt"
  product_name <- "Champion Women's Classic Tee"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev15 <- rbind(productrev15, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev15, file = "product15.csv")
```

Product 16
```{r}
productrev16 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Levis-Womens-Perfect-T-Shirt-Persimmon/product-reviews/B07VD3TXYT/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "T-shirt"
  product_name <- "Levi's Women's The Perfect Tee"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev16 <- rbind(productrev16, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev16, file = "product16.csv")
```

Product 17
```{r}
productrev17 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Urban-CoCo-Womens-Versatile-Stretchy/product-reviews/B0CGQH1M8X/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Skirt"
  product_name <- "Urban CoCo Women's Basic Versatile Stretchy Flared Casual Mini Skater Skirt"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev17 <- rbind(productrev17, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev17, file = "product17.csv")
```

Product 18
```{r}
productrev18 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/ZESICA-Bohemian-Printed-Elastic-Pockets/product-reviews/B07K2RHCGF/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Skirt"
  product_name <- "ZESICA Women's 2023 Bohemian Floral Printed Elastic Waist A Line Maxi Skirt with Pockets"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev18 <- rbind(productrev18, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev18, file = "product18.csv")
```

Product 19
```{r}
productrev19 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/luvamia-Skorts-Waisted-Stretchy-Brilliant/product-reviews/B0BX7CXW8Q/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Skirt"
  product_name <- "luvamia Skorts Skirts for Women Denim Mini Skirt Side Slit with High Waisted Jean Shorts Stretchy"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev19 <- rbind(productrev19, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev19, file = "product19.csv")
```

Product 20
```{r}
productrev20 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/TONCHENGSD-Womens-Gothic-Pleated-Waisted/product-reviews/B08TG5DBFG/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Skirt"
  product_name <- "TONCHENGSD Women's Gothic Punk Plaid Pleated High Waisted Short A-line Flare Mini Skirt"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev20 <- rbind(productrev20, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev20, file = "product20.csv")
```

Product 21
```{r}
productrev21 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/DC-Comics-Womens-Metallic-T-Shirt/product-reviews/B07KYZL4Y5/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "T-shirt"
  product_name <- "DC Comics Women's Wonder Woman Metallic Logo"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev21 <- rbind(productrev21, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev21, file = "product21.csv")
```

Product 22
```{r}
productrev22 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/GAP-Womens-Crewneck-Favorite-T-Shirt/product-reviews/B0BGN6RBQD/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "T-shirt"
  product_name <- "GAP Women's 2-Pack Crewneck Favorite Tee T-Shirt"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev22 <- rbind(productrev22, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev22, file = "product22.csv")
```

Product 23
```{r}
productrev23 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/CALVIN-KLEIN-Womens-Embroidery-Bright/product-reviews/B07ZGDKB5F/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "T-shirt"
  product_name <- "Calvin Klein Jeans Women's CKJ CK EMBROIDERY SLIM T YAF WHT WMN TEE"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev23 <- rbind(productrev23, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev23, file = "product23.csv")
```

Product 24
```{r}
productrev24 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Nike-Womens-Essential-Futur-T-Shirt/product-reviews/B07FKBPY9R/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "T-shirt"
  product_name <- "Nike Women's Tee Essential Icon Futur T-Shirt"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev24 <- rbind(productrev24, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev24, file = "product24.csv")
```

Product 25
```{r}
productrev25 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Russell-Athletic-Womens-Essential-Heather/product-reviews/B073X69XWP/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "T-shirt"
  product_name <- "Russell Athletic Womens Essential Short Sleeve T-Shirt"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev25 <- rbind(productrev25, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev25, file = "product25.csv")
```

Product 26
```{r}
productrev26 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Skechers-Womens-Uno-Stand-Trainers-White/product-reviews/B0CRZD9PLZ/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shoes"
  product_name <- "Skechers Uno Stand On Air Womens"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev26 <- rbind(productrev26, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev26, file = "product26.csv")
```

product 27
```{r}
productrev27 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Skechers-Womens-Street-Uno-Durabuck/product-reviews/B07WG9RVYK/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shoes"
  product_name <- "Skechers Women's Uno - Night Shades Lace-Up Sneaker"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev27 <- rbind(productrev27, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev27, file = "product27.csv")
```

Product 28
```{r}
productrev28 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Dickies-Mens-Loose-Multi-Pocket-Short/product-reviews/B0CW3F4JTT/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Dickies Men's 13 Inch Loose Fit Multi-Pocket Work Short"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev28 <- rbind(productrev28, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev28, file = "product28.csv")
```

```{r}
productrev29 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/1994Fashion-Compression-Athletic-Baselayer-Underwear/product-reviews/B087V2GR6C/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "ZENGVEE 3 Pack Men's Compression Shorts Cool Dry Running Base Layer Shorts with Phone Pockets for Running,Training, Workout, Gym"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev29 <- rbind(productrev29, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev29, file = "product29.csv")
```

```{r}
productrev30 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Nike-BV6855/product-reviews/B081PCJ7XN/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Nike"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev30 <- rbind(productrev30, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev30, file = "product30.csv")
```

```{r}
productrev31 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Champion-81622-Mens-Long-Mesh/product-reviews/B0CRDWLYYG/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Champion Men's Long Mesh"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev31 <- rbind(productrev31, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev31, file = "product31.csv")
```

```{r}
productrev32 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Under-Armour-HeatGear-Compression-Shorts/product-reviews/B0BYDJW7LT/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Under Armour Men's Armour HeatGear Compression Shorts"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev32 <- rbind(productrev32, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev32, file = "product32.csv")
```

```{r}
productrev33 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Wrangler/product-reviews/B0C4YMLM2N/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Wrangler"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev33 <- rbind(productrev33, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev33, file = "product33.csv")
```

```{r}
productrev34 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Lee-Dungarees-Belted-Wyoming-Cargo/product-reviews/B089M8J461/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Lee Men's Dungarees New Belted Wyoming Cargo Short"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev34 <- rbind(productrev34, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev34, file = "product34.csv")
```


```{r}
productrev35 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Canterbury-Advantage-Short/product-reviews/B077K29BJN/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Canterbury Advantage Short"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev35 <- rbind(productrev35, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev35, file = "product35.csv")
```

```{r}
productrev36 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Wrangler-Authentics-Classic-Relaxed-Pocket/product-reviews/B0CR6HS22S/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Wrangler Authentics Men's Classic Relaxed Fit Five Pocket Jean"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev36 <- rbind(productrev36, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev36, file = "product36.csv")
```

```{r}
productrev37 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/NAUTICA-Classic-Front-Stretch-Solid/product-reviews/B09S7298J6/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Nautica Men's Classic Fit Flat Front Stretch Solid Chino Deck Short"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev37 <- rbind(productrev37, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev37, file = "product37.csv")
```

```{r}
productrev38 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Volcom-Vmonty-Stretch-Chino-Short/product-reviews/B082TJ68BZ/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Volcom"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev38 <- rbind(productrev38, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev38, file = "product38.csv")
```

```{r}
productrev39 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/LEE-Extreme-Motion-Swope-Cargo/product-reviews/B06WVSSLJ8/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Lee Mens 21861 Extreme Motion Swope Cargo Short Cargo Shorts"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev39 <- rbind(productrev39, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev39, file = "product39.csv")
```

```{r}
productrev40 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/UNIONBAY-Survivor-Belted-Cargo-Short-Reg/product-reviews/B01MT8MQBT/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "UNIONBAY Men's Survivor Belted Cargo Short-Reg and Big & Tall Sizes"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev40 <- rbind(productrev40, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev40, file = "product40.csv")
```

```{r}
productrev41 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Liberty-Imports-Athletic-Basketball-Activewear/product-reviews/B07VPL7FH7/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Liberty Imports Pack of 5 Men's Athletic Basketball Shorts Mesh Quick Dry Activewear with Pockets"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev41 <- rbind(productrev41, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev41, file = "product41.csv")
```

```{r}
productrev42 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Russell-Athletic-Mens-Short-Pockets/product-reviews/B07C8778DX/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Russell Athletic Men's Mesh Short with Pockets"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev42 <- rbind(productrev42, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev42, file = "product42.csv")
```

```{r}
productrev43 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Under-Armour-Short-Bottoms-Shorts/product-reviews/B0BN7SGQX2/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Under Armour UA Tech Short, Mens, Bottoms, Shorts, 10 in"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev43 <- rbind(productrev43, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev43, file = "product43.csv")
```

```{r}
productrev44 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/MCPORO-Gym-Shorts-Men-Comfortable/product-reviews/B098FK9DSS/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "MCPORO Gym Shorts for Men  Comfortable Quick Dry Mens Athletic Shorts"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev44 <- rbind(productrev44, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev44, file = "product44.csv")
```

```{r}
productrev45 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/LEE-Mens-Carpenter-Jean-Short/product-reviews/B09PBXGMSM/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "LEE Men's Carpenter Jean Short"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev45 <- rbind(productrev45, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev45, file = "product45.csv")
```

```{r}
productrev46 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Russell-Athletic-Cotton-Baseline-Pockets/product-reviews/B07HXDCCJ1/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Russell Athletic Men's Cotton Baseline Short with Pockets"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev46 <- rbind(productrev46, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev46, file = "product46.csv")
```

```{r}
productrev47 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Under-Armour-Mens-Graphic-Shorts/product-reviews/B071P2NZ91/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "Under Armour Men's UA Tech Graphic Short"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev47 <- rbind(productrev47, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev47, file = "product47.csv")
```

```{r}
productrev48 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/CARHARTT-Force-Relaxed-Ripstop-Cargo/product-reviews/B0BZL69LZM/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Shorts"
  product_name <- "CARHARTT Men's Force Relaxed Fit Ripstop Cargo Work Short"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev48 <- rbind(productrev48, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev48, file = "product48.csv")
```

```{r}
productrev49 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/HP-Display-Graphics-Keyboard-Microsoft/product-reviews/B09MDGXHMF/ref=cm_cr_dp_d_show_all_btm", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Electronics"
  product_name <- "HP Stream Laptop | 11.6 Inch HD Display | Intel Celeron N4120 | 4GB DDR4 RAM | 64GB eMMC | Intel Graphics | Windows 11 S-Mode | QWERTZ Keyboard | White | Includes Microsoft Office 365 Single"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev49 <- rbind(productrev49, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev49, file = "product49.csv")
```

```{r}
productrev50 <- data.frame()
for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Lenovo-Ideapad-WideView-Anti-Glare-Graphics/product-reviews/B09RPRSS19/ref=cm_cr_dp_d_show_all_btm", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  product_category <- "Electronics"
  product_name <- "Lenovo Ideapad 3 Slim Laptop | 14 Inch Full HD WideView Display Anti-Glare | AMD Ryzen 5 5500U | 8GB RAM | 512GB SSD | AMD Radeon Graphics | Windows 11 Home | Grey"
  verified_reviews <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]
  product_reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  product_review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  product_date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  product_rating <- scrapeNodes("span.a-icon-alt")[1:10]

  productrev50 <- rbind(productrev50, data.frame(
                      category = product_category,
                      name = product_name,
                      reviewer = product_reviewer,
                      reviews = product_review,
                      verified = verified_reviews,
                      "date of review" = product_date,
                      ratings = product_rating))
  Sys.sleep(3)
}
write.csv(productrev50, file = "product50.csv")
```
